export const GET_MOVIE_SIMILAR = {
  path: `/movie/233123/similar?api_key=29837691283`,
  status: 200,
  data: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: '/8uVKfOJUhmybNsVh089EqLHUYEG.jpg',
        genre_ids: [Array],
        id: 693134,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Dune: Part Two',
        overview:
          'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
        popularity: 1990.512,
        poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        release_date: '2024-02-27',
        title: 'Dune: Part Two',
        video: false,
        vote_average: 8.262,
        vote_count: 3452,
      },
      {
        adult: false,
        backdrop_path: '/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg',
        genre_ids: [Array],
        id: 937287,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Challengers',
        overview:
          'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
        popularity: 531.851,
        poster_path: '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
        release_date: '2024-04-18',
        title: 'Challengers',
        video: false,
        vote_average: 7.414,
        vote_count: 185,
      },
      {
        adult: false,
        backdrop_path: '/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg',
        genre_ids: [Array],
        id: 948549,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Love Lies Bleeding',
        overview:
          'Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.',
        popularity: 243.412,
        poster_path: '/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg',
        release_date: '2024-03-08',
        title: 'Love Lies Bleeding',
        video: false,
        vote_average: 7.141,
        vote_count: 85,
      },
      {
        adult: false,
        backdrop_path: '/lA6KdSkCTxwzvqzPqxch997RabQ.jpg',
        genre_ids: [Array],
        id: 560016,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Monkey Man',
        overview:
          'Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.',
        popularity: 502.284,
        poster_path: '/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg',
        release_date: '2024-04-03',
        title: 'Monkey Man',
        video: false,
        vote_average: 7.271,
        vote_count: 258,
      },
      {
        adult: false,
        backdrop_path: '/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg',
        genre_ids: [Array],
        id: 934632,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Rebel Moon — Part Two: The Scargiver',
        overview:
          'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.',
        popularity: 2477.048,
        poster_path: '/cxevDYdeFkiixRShbObdwAHBZry.jpg',
        release_date: '2024-04-19',
        title: 'Rebel Moon — Part Two: The Scargiver',
        video: false,
        vote_average: 6.137,
        vote_count: 550,
      },
      {
        adult: false,
        backdrop_path: '/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg',
        genre_ids: [Array],
        id: 618588,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Arthur the King',
        overview:
          'Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.',
        popularity: 1308.397,
        poster_path: '/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg',
        release_date: '2024-03-15',
        title: 'Arthur the King',
        video: false,
        vote_average: 6.707,
        vote_count: 70,
      },
      {
        adult: false,
        backdrop_path: '/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg',
        genre_ids: [Array],
        id: 438631,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Dune',
        overview:
          "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
        popularity: 627.288,
        poster_path: '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
        release_date: '2021-09-15',
        title: 'Dune',
        video: false,
        vote_average: 7.79,
        vote_count: 11434,
      },
      {
        adult: false,
        backdrop_path: '/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg',
        genre_ids: [Array],
        id: 866398,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'The Beekeeper',
        overview:
          "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
        popularity: 458.009,
        poster_path: '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg',
        release_date: '2024-01-08',
        title: 'The Beekeeper',
        video: false,
        vote_average: 7.457,
        vote_count: 2180,
      },
      {
        adult: false,
        backdrop_path: '/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg',
        genre_ids: [Array],
        id: 929590,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Civil War',
        overview:
          'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
        popularity: 723.121,
        poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        release_date: '2024-04-10',
        title: 'Civil War',
        video: false,
        vote_average: 7.407,
        vote_count: 482,
      },
      {
        adult: false,
        backdrop_path: '/8zkL012HdOiGQOCBNo04CD45hZo.jpg',
        genre_ids: [Array],
        id: 762509,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Mufasa: The Lion King',
        overview:
          'Rafiki relays the legend of Mufasa to lion cub Kiara, daughter of Simba and Nala. Told in flashbacks, the story introduces Mufasa as an orphaned cub, lost and alone until he meets a sympathetic lion named Taka—the heir to a royal bloodline. The chance meeting sets in motion a journey of misfits searching for their destiny and working together to evade a threatening and deadly foe.',
        popularity: 16.709,
        poster_path: '/9bXHaLlsFYpJUutg4E6WXAjaxDi.jpg',
        release_date: '2024-12-18',
        title: 'Mufasa: The Lion King',
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: '/aINel9503ompOlGKn4sIVMg09Un.jpg',
        genre_ids: [Array],
        id: 838209,
        media_type: 'movie',
        original_language: 'ko',
        original_title: '파묘',
        overview:
          "After tracing the origin of a disturbing supernatural affliction to a wealthy family's ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.",
        popularity: 367.942,
        poster_path: '/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg',
        release_date: '2024-02-22',
        title: 'Exhuma',
        video: false,
        vote_average: 7.684,
        vote_count: 57,
      },
      {
        adult: false,
        backdrop_path: '/6VoxDupaW2VXfLtJyeOoGCgXSjD.jpg',
        genre_ids: [Array],
        id: 1116490,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Cash Out',
        overview:
          'Criminal mastermind Mason is about to execute the score of a lifetime when his lover and key member of his crew, Decker, takes the team down and reveals she’s an undercover Interpol agent. Heartbroken, Mason escapes and retires from the life of crime until his younger brother Shawn is out of his league taking on a big bank heist all on his own. Mason has no choice left but to come to the rescue, while Interpol brings Decker in hoping to unnerve him. Before the SWAT teams storm the bank, Mason must use every tool in his arsenal to not only escape with the prize, but also the love of his life.',
        popularity: 146.361,
        poster_path: '/v3youHDLigrtIis1NqTjlY8Sk38.jpg',
        release_date: '2024-04-26',
        title: 'Cash Out',
        video: false,
        vote_average: 6.733,
        vote_count: 14,
      },
      {
        adult: false,
        backdrop_path: '/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg',
        genre_ids: [Array],
        id: 1011985,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Kung Fu Panda 4',
        overview:
          'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
        popularity: 2020.311,
        poster_path: '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
        release_date: '2024-03-02',
        title: 'Kung Fu Panda 4',
        video: false,
        vote_average: 7.162,
        vote_count: 1382,
      },
      {
        adult: false,
        backdrop_path: '/AuTfo1lbE8s2Y8RVTmlbJAeLWPK.jpg',
        genre_ids: [Array],
        id: 850888,
        media_type: 'movie',
        original_language: 'es',
        original_title: 'Sayen: La Cazadora',
        overview:
          "The action-packed thriller follows the journey of Sayen, a Mapuche woman who uncovers a dangerous conspiracy led by an international corporation that is destroying her family's land and ravaging the local ecosystems throughout Chile, and takes it upon herself to bring these people to justice and save her family's legacy.",
        popularity: 83.245,
        poster_path: '/77a96CjyAZik5QrdgNzObLtmoxb.jpg',
        release_date: '2024-04-26',
        title: 'Sayen: The Huntress',
        video: false,
        vote_average: 7.25,
        vote_count: 12,
      },
      {
        adult: false,
        backdrop_path: '/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg',
        genre_ids: [Array],
        id: 823464,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Godzilla x Kong: The New Empire',
        overview:
          'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
        popularity: 2372.572,
        poster_path: '/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg',
        release_date: '2024-03-27',
        title: 'Godzilla x Kong: The New Empire',
        video: false,
        vote_average: 6.64,
        vote_count: 798,
      },
      {
        adult: false,
        backdrop_path: '/8PyV1YsO0ZPHZug9aEe363UUwed.jpg',
        genre_ids: [Array],
        id: 914215,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Humane',
        overview:
          "In the wake of an environmental collapse that has forced humanity to shed 20% of its population, a family dinner erupts into chaos when a father's plan to enlist in the government's new euthanasia program goes horribly awry.",
        popularity: 164.517,
        poster_path: '/ecOvKaoM1hwQbp0uTnULGrSV32e.jpg',
        release_date: '2024-04-26',
        title: 'Humane',
        video: false,
        vote_average: 5.4,
        vote_count: 15,
      },
      {
        adult: false,
        backdrop_path: '/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg',
        genre_ids: [Array],
        id: 845111,
        media_type: 'movie',
        original_language: 'fr',
        original_title: 'Les trois mousquetaires : Milady',
        overview:
          "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
        popularity: 1352.91,
        poster_path: '/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg',
        release_date: '2023-12-13',
        title: 'The Three Musketeers: Milady',
        video: false,
        vote_average: 6.532,
        vote_count: 349,
      },
      {
        adult: false,
        backdrop_path: '/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg',
        genre_ids: [Array],
        id: 1209288,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Justice League: Crisis on Infinite Earths Part Two',
        overview:
          'An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?',
        popularity: 790.506,
        poster_path: '/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg',
        release_date: '2024-04-22',
        title: 'Justice League: Crisis on Infinite Earths Part Two',
        video: false,
        vote_average: 6.216,
        vote_count: 37,
      },
      {
        adult: false,
        backdrop_path: '/4yrOyO3N55XazHQXXYoqiiPQd40.jpg',
        genre_ids: [Array],
        id: 938614,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Late Night with the Devil',
        overview:
          "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
        popularity: 810.306,
        poster_path: '/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg',
        release_date: '2024-03-19',
        title: 'Late Night with the Devil',
        video: false,
        vote_average: 7.306,
        vote_count: 245,
      },
      {
        adult: false,
        backdrop_path: '/5cCfqeUH2f5Gnu7Lh9xepY9TB6x.jpg',
        genre_ids: [Array],
        id: 967847,
        media_type: 'movie',
        original_language: 'en',
        original_title: 'Ghostbusters: Frozen Empire',
        overview:
          "The Spengler family returns to where it all started – the iconic New York City firehouse – to team up with the original Ghostbusters, who've developed a top-secret research lab to take busting ghosts to the next level. But when the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
        popularity: 425.019,
        poster_path: '/6faYaQyiBPhqAizldJKq21mIVaE.jpg',
        release_date: '2024-03-20',
        title: 'Ghostbusters: Frozen Empire',
        video: false,
        vote_average: 6.415,
        vote_count: 349,
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
};
